client/components/products.js
client/store/products.js

Products aleks fixed sort

---

client/components/DisplaySearch.js
client/components/navbar.js
client/components/products.js
client/routes.js
client/store/divided.js
client/store/pagesCategories.js
client/store/products.js
client/store/searchItem.js
package-lock.json
package.json

links work

---

client/components/user-home/user-actions/product-create.js
client/routes.js
script/seed.js
server/api/products.js

Minor updates and added seed data.

Katt updates

---

client/components/cart.js
client/components/navbar.js
client/components/orders.js
client/components/products.js
client/routes.js
client/store/cart.js
client/store/index.js
client/store/orders.js
client/store/products.js
server/api/index.js
server/api/orders.js
server/db/models/index.js
server/db/models/orderitem.js
server/index.js

started orders no cart

---

client/components/DisplayByCategory.js
client/components/Search.js
client/components/modelPopup.js
client/components/navbar.js
client/components/orders.js
client/store/orders.js
public/style.css

css addition, just to make it more clear for now

---

client/components/navbar.js
server/api/orders.js
server/db/models/orderitem.js
server/index.js

Products aleks

---

client/components/user-home/user-actions/product-create-update.js
client/components/user-home/user-admin-comps/product-list.js
client/components/user-home/user-admin-comps/user-list.js
public/style.css

- Updates to admin product create/update

Katt - updates to admin product create/update

---

client/components/user-home/user-actions/product-create-update.js
client/components/user-home/user-actions/user-update.js
client/components/user-home/user-admin-comps/product-list.js
client/components/user-home/user-admin-comps/user-list.js
client/components/user-home/user-home.js
client/components/user-home/user-home.spec.js
client/routes.js
client/store/products.js
client/store/users.js
public/style.css
server/api/products.js
server/api/users.js
server/db/models/index.js

- Updates to product-list functionality
- Updates to user-list functionality

Katt - updates to admin user-list & product-list

---

client/components/orders.js
client/components/product.js
client/store/orderItems.js
client/store/orders.js

Products aleks orders and all items are there for user in a cart now, but i think defently the way we set the store for orders might be bad

---

client/components/orders.js
client/store/orderItems.js
public/style.css
server/api/orderItems.js
server/api/orders.js

edit delete work, but buttons functionality not finished

---

client/components/orders.js

Products aleks clean up mostly

---

script/seed.js

Katt - Add order, orderitems to cody

---

client/store/orderItems.js
server/db/models/order.js
server/db/models/user.js

Edits to models and store

---

client/components/navbar.js
client/components/orders.js
client/components/product.js
client/routes.js
client/store/order.js
server/api/orders.js
server/db/models/index.js

Products aleks, guest user can shop

---

client/components/user-home/user-actions/order-update.js
client/components/user-home/user-comps/orders.js
client/components/user-home/user-home.js
client/store/orders.js
server/api/orders.js

- Remove nav HomeCarousel
- Add img to Category model
- Add order history to user account

Add orders page to user home

---

client/components/orders.js
client/components/product.js
client/components/products.js
client/routes.js
client/store/order.js
client/store/orderItems.js

works not fully

---

client/app.js
client/components/DisplayByCategory.js
client/components/DisplaySearch.js
client/components/helpers.js
client/components/home/HomeFooter.js
client/components/home/home.js
client/components/products.js
client/components/user-home/user-admin-comps/product-list.js
client/components/user-home/user-comps/reviews.js
client/store/products.js
client/store/users.js
public/style.css
server/api/products.js
server/db/models/index.js

- Add header to cards
- Format photos to be the same size
- Move footer to bottom of app
- Add ratings to products
- Minor style edits

Katt - updates cosmetic changes

---

client/components/Checkout.js
client/components/navbar.js
client/components/product.js
client/routes.js
public/common.css

cart works, please check on your browser 

---

client/components/user-home/user-comps/reviews.js
client/store/order.js
client/store/orderItems.js
public/style.css
server/api/products.js

Katt - fix syncing issues in store

---

client/store/order.js

Fix add order issue

---

public/common.css
script/seed.js

Katt - Edit seed

---

client/components/navbar.js
client/components/orders.js
client/components/product.js
client/store/order.js
client/store/product.js
public/style.css
server/api/orders.js
server/api/products.js

checkout button,updates order with total, and status.and quantity in product, and link to '/checkout'

---

client/components/Checkout.js
client/components/OrderSummary.js
client/components/orders.js
client/routes.js
server/index.js

wip stripe

---

client/components/Loader.js
client/components/helpers.js
client/components/products.js
client/store/products.js

Products aleks,sort fixed

---

client/components/Checkout.js
server/index.js

Update to checkout

---

client/components/Checkout.js
server/index.js

Remove user email

---

client/components/helpers.js
client/components/navbar.js
client/components/orders.js
client/components/product.js
client/components/products.js
client/components/user-home/user-home.js

cart updated

---

client/components/home/HomeCarousel.js
client/components/home/categoryBar.js
client/components/home/home.js
client/components/navbar.js
client/components/products.js
public/index.html

fixed scrips.js

---

client/app.js
client/components/DisplayByCategory.js
client/components/OrderSummary.js
client/components/ProductCard.js
client/components/Search.js
client/components/helpers.js
client/components/home/Footer.js
client/components/home/HomeCarousel.js
client/components/home/home.js
client/components/navbar.js
client/components/orders.js
client/components/product.js
client/components/products.js
client/components/user-home/user-home.js
client/store/order.js
public/index.html
public/style.css

checkout added and other fixes

---

client/components/OrderSummary.js
client/components/auth-form.js
client/components/navbar.js
client/components/orders.js

hamburger menu fix

---

client/components/ContactPage.js
client/components/navbar.js
client/routes.js

contact page

---

client/components/DisplayByCategory.js
client/components/OrderSummary.js
client/components/auth-form.js
client/components/navbar.js
client/components/product.js
client/store/order.js

some fixes

---

client/components/products.js
client/components/user-home/user-home.js

Aleks branch

---

public/index.html

Add metadata image and description

---

client/components/user-home/user-home.js
server/db/db.js
server/index.js

User dashboard
